version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: DrepsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VpjsqbJFnkIkyMuSQgbXExyhfXmRJqoi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: dresp_api
    environment:
      DB_URL: jdbc:postgresql://nozomi.proxy.rlwy.net:23844/railway
      DB_USER: postgres
      DB_PASSWORD: VpjsqbJFnkIkyMuSQgbXExyhfXmRJqoi
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
